let data = [
  {
    Name: "Saray Erkek Öğrenci Yurdu Gebze",
    Type: 2,
    MonthlyPrice: [
      {
        RoomInfo: "Bilinmiyor",
        Price: "",
      },
    ],
    YearlyPrice: "Bilinmiyor",
    TotalCapacity: "Bilinmiyor",
    FoodStates: "Bilinmiyor",
    TelephoneNumbers: ["0553 352 28 53"],
    Address: "Adem Yavuz 2334/3. Sokak No:2 41400 Gebze/Kocaeli",
    OtherInfo: "Süleymancılar vakıf yurdudur.",
    Comments: [],
    Deposit: "Bilinmiyor",
    GenderType: 1,
    Images: [
      "https://i.ibb.co/dmpsgjD/69.jpg",
      "https://i.ibb.co/X3NLRMM/68.jpg",
      "https://i.ibb.co/ns8b2bb/66.jpg",
      "https://i.ibb.co/52wy3xg/67.jpg",
      "https://lh3.googleusercontent.com/p/AF1QipMmYTnXb8U_lx-xroDjZNdb39LfSOl-nUcgu751=w1080-h608-p-no-v0",
    ],
  },
  {
    Name: "İlim Yayma Cemiyeti Gebze Yükseköğretim Erkek Öğrenci Yurdu",
    Type: 2,
    MonthlyPrice: [
      {
        RoomInfo: "Bilinmiyor",
        Price: "",
      },
    ],
    YearlyPrice: "Bilinmiyor",
    TotalCapacity: "Bilinmiyor",
    FoodStates: "Bilinmiyor",
    TelephoneNumbers: ["0262 742 05 08"],
    Address:
      "Adem Yavuz Mah. Yavuz Sultan Selim Cad. 2334/4 Sok. No:26 Gebze/Kocaeli",
    OtherInfo: "Vakıf yurdudur.",
    Comments: [],
    Deposit: "Bilinmiyor",
    GenderType: 1,
    Images: [
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8804.JPG",
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8801.JPG",
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8719.JPG",
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8780.JPG",
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8769.JPG",
      "https://iyc.org.tr/files/yurt_foto/51068/kucuk_dosyalar/VA5B8663.JPG",
    ],
  },
  {
    Name: "Tuzla Eva Derin Öğrenci Evi",
    Type: 2,
    MonthlyPrice: [
      {
        RoomInfo: "2 Kişilik",
        Price: "1800",
      },
    ],
    YearlyPrice: "Bilinmiyor",
    TotalCapacity: "Bilinmiyor",
    FoodStates: "Yemek yok. Mutfak var",
    TelephoneNumbers: ["0505 689 50 26"],
    Address: "Postane, Muhacir Sk. No:5, 34940 Tuzla/İstanbul",
    OtherInfo: "Pansiyon şeklindedir. Sadece Erkek Öğrencileri içindir",
    Comments: [],
    Deposit: "Bilinmiyor",
    GenderType: 2,
    Images: [
      "https://lh3.googleusercontent.com/iqLNzuUO-p-ai2H6Xi51a6wkz0cu8hD0GqUDGfM4JUY325hnnizgR1N7mhVYOqj5Gm4Nr-VccdpbL2c7=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/vy4hJuyNWttT81AJpoW3AN8-PeR9QY7NvzNrO_hdSOQ10sGZBmxVIhhuJtVWstaXSHIEVZdJKMPkeHv1=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/xiRtqz6RlQNHCazL6wGLuTEJbjzxG8_vgYd4sZC7rGHAgkkv8twVZH_ioJBPyFZDWMICdg5SEze-0ZUQ=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/mkbl6HCZ-1NmMFd-FQQJ0qUKB7qg_gukDX-1uxdSdUvZSKqkjYCz_u0UwrZKqliLKlNXIeXmDBPFYXNg=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/VeBHodVEEtX9koLq_KP9Hid9tI2JUFqSTfEFOFt1M0FZ04ah0P6bYIpe0Ul04yCK8K_XOMISqHL6ptDi=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/qlauoYDi7_hAoHp1psSnmtpt50tNnmwjGFnTumrBvkfsj82OzL3dA0fy2ms1JXGPnUcG9-54YJb-9bUt=w284-h284-n-rw-no-v1",
      "https://lh3.googleusercontent.com/3EUb6bMqdHc56lFZXIcYZvhrPSaFwxR3TrN07wVq_ltjqaaUjIql2urSIuCJKc0ljp_dHiDarC_teyhf=w284-h284-n-rw-no-v1",
    ],
  },
];
export default data;
